function G = out_G(theta1,theta2,dtheta1,dtheta2)
%OUT_G
%    G = OUT_G(THETA1,THETA2,DTHETA1,DTHETA2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    18-Jan-2017 20:57:01

t2 = sin(theta1);
t3 = cos(theta2);
t4 = cos(theta1);
t5 = sin(theta2);
G = [t2.*(-9.81e2./2.0e2)-t2.*t3.*(2.943e3./2.0e2)-t4.*t5.*(9.81e2./2.0e2)+t2.*(t3-1.0).*(9.81e2./1.0e2);t2.*t3.*(-9.81e2./2.0e2)-t4.*t5.*(9.81e2./2.0e2)];
