function C = out_C(theta1,theta2,dtheta1,dtheta2)
%OUT_C
%    C = OUT_C(THETA1,THETA2,DTHETA1,DTHETA2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    18-Jan-2017 20:57:01

C = reshape([0.0,0.0,0.0,0.0],[2, 2]);
