function E = out_E(theta1,theta2,dtheta1,dtheta2)
%OUT_E
%    E = OUT_E(THETA1,THETA2,DTHETA1,DTHETA2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    18-Jan-2017 20:57:01

t2 = cos(theta1);
t3 = cos(theta2);
E = t2.*(9.81e2./2.0e2)-sin(theta1).*sin(theta2).*(9.81e2./2.0e2)+t2.*t3.*(2.943e3./2.0e2)-t2.*(t3-1.0).*(9.81e2./1.0e2)+dtheta1.*(dtheta1.*(1.0./1.2e1)+dtheta2.*(1.0./2.4e1))+dtheta2.*(dtheta1.*(1.0./2.4e1)+dtheta2.*(1.3e1./2.4e1));
