function D = out_D(theta1,theta2,dtheta1,dtheta2)
%OUT_D
%    D = OUT_D(THETA1,THETA2,DTHETA1,DTHETA2)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    18-Jan-2017 20:57:01

D = reshape([1.0./6.0,1.0./1.2e1,1.0./1.2e1,1.3e1./1.2e1],[2, 2]);
